import STPDCore
import SwiftUI

/// Standalone view for the distribution-first foundation (D1-D3). It renders a pre-shaped
/// `ISIDistributionFoundationPresentation` (from STPDCore) and depends ONLY on STPDCore + SwiftUI —
/// deliberately NO `RasterDocument` / `WorkbenchSection` dependency, so it compiles and previews
/// without the (currently dirty) Workbench nav files. Navigation wiring is a separate later step.
///
/// This is the distribution-first counterpart to the old QC `DatasetISIHistogramView`, and is clearly
/// labelled as such.
struct ISIDistributionFoundationView: View {
    let presentation: ISIDistributionFoundationPresentation

    /// Trains selected for the stacked composition (UI-2C). Held as local `@State` so the control is
    /// self-contained — deliberately NOT wired to Workbench selection yet. Stale ids are harmless:
    /// `selectedDetails` filters against the current presentation.
    @State private var selectedTrainIDs: Set<String> = []

    /// How many trains the "Top N" quick action selects (by valid-ISI count).
    private let topN = 5

    /// The selected trains in stable `perTrainDetails` order (stacking order + color index), with stale
    /// ids dropped so the control stays consistent after a dataset swap.
    private var selectedDetails: [ISIDistributionTrainDetail] {
        presentation.selectedTrainDetails(selectedTrainIDs)
    }

    /// Selected trains paired with their stable colors, in stacking order — what the chart draws.
    private var stackedTrains: [(detail: ISIDistributionTrainDetail, color: Color)] {
        selectedDetails.map { ($0, trainColor($0.trainID)) }
    }

    /// The train whose detailed priors are drawn on the chart (UI-2D). Requested via `focusedTrainID`,
    /// but always constrained to the selected set (defaults to the first selected train, and falls back
    /// there when its train is deselected). `nil` when nothing is selected.
    @State private var focusedTrainID: String?

    private var focusedDetail: ISIDistributionTrainDetail? {
        presentation.focusedTrainDetail(requested: focusedTrainID, within: selectedTrainIDs)
    }

    /// Focus-picker binding reflecting the EFFECTIVE focus, so the control always shows the train whose
    /// priors are on the chart (even when the request defaulted/fell back).
    private var focusSelection: Binding<String?> {
        Binding(get: { focusedDetail?.trainID }, set: { focusedTrainID = $0 })
    }

    /// TSW-2 candidates (debug-only, unwired) for a given train.
    private func tswCandidates(for trainID: String) -> [TSWCandidateRow] {
        presentation.tswCandidatesByTrainID[trainID] ?? []
    }

    /// TSW candidates for the focused train — the only ones overlaid on the chart (to avoid clutter).
    private var focusedTSWCandidates: [TSWCandidateRow] {
        focusedDetail.map { tswCandidates(for: $0.trainID) } ?? []
    }

    /// Curated per-train palette, deliberately avoiding the family band hues (burst=orange, tonic=green,
    /// pause=blue) so train stacks read distinctly against the bands. Used for the first N trains.
    private static let trainPalette: [Color] = [.pink, .purple, .brown, .indigo, .red, .yellow, .teal, .mint, .cyan]

    /// Stable color for a train, keyed by its index in `perTrainDetails` — so a train keeps its color
    /// regardless of which others are selected. The curated palette covers the common case; beyond it,
    /// colors are generated by golden-angle hue spacing so 10+ trains still get DISTINCT (if less
    /// curated) colors rather than wrapping back onto `palette[0…]` and colliding.
    private func trainColor(_ trainID: String) -> Color {
        guard let idx = presentation.perTrainDetails.firstIndex(where: { $0.trainID == trainID }) else { return .gray }
        if idx < Self.trainPalette.count { return Self.trainPalette[idx] }
        let overflow = idx - Self.trainPalette.count
        let hue = (0.618_033_988_75 * Double(overflow + 1)).truncatingRemainder(dividingBy: 1.0)
        return Color(hue: hue,
                     saturation: overflow.isMultiple(of: 2) ? 0.85 : 0.60,
                     brightness: overflow.isMultiple(of: 2) ? 0.80 : 0.98)
    }

    /// Convenience for the eventual nav call site (and the preview): shape the presentation from a
    /// dataset, preferring a D2-wired run distribution when available.
    init(dataset: SpikeDataset, runDistribution: DatasetISIDistribution?, minimumValidISISec: Double) {
        self.init(presentation: .from(dataset: dataset, runDistribution: runDistribution, minimumValidISISec: minimumValidISISec))
    }

    init(presentation: ISIDistributionFoundationPresentation) {
        self.presentation = presentation
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                header
                if presentation.pooledValidISICount == 0 && presentation.perTrain.isEmpty {
                    emptyState
                } else {
                    selectedTrainControl
                    chartSection
                    selectedTrainPriorsSection
                    tswCandidatesSection
                    quantileSection
                    perTrainSection
                    intervalSection
                }
            }
            .padding(20)
            .frame(maxWidth: .infinity, alignment: .topLeading)
        }
    }

    // MARK: Header

    private var header: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(alignment: .firstTextBaseline, spacing: 10) {
                Image(systemName: "chart.bar.doc.horizontal")
                    .foregroundStyle(.secondary)
                Text("Distribution-first foundation (D1-D3)")
                    .font(.title3.weight(.semibold))
                badge(sourceText, tint: presentation.source == .detectionRun ? .green : .orange)
                Spacer()
            }
            Text("Distribution-first ISI models (D1/D2) + D3-derived burst/tonic/pause interval priors — separate from the old QC ISI histogram.")
                .font(.callout)
                .foregroundStyle(.secondary)
            HStack(spacing: 14) {
                metric("Dataset", presentation.datasetName)
                metric("Floor", "\(ms(presentation.floorSec)) ms")
                metric("Contributing trains", "\(presentation.contributingTrainCount)")
                metric("Pooled valid ISIs", "\(presentation.pooledValidISICount)")
            }
            .font(.caption)
        }
    }

    private var sourceText: String {
        switch presentation.source {
        case .detectionRun: return "from detection run"
        case .computedFromDataset: return "computed from dataset"
        }
    }

    // MARK: Sections

    private var quantileSection: some View {
        sectionCard("Dataset quantiles (seconds → ms)") {
            Grid(alignment: .leading, horizontalSpacing: 14, verticalSpacing: 6) {
                quantileHeaderRow
                Divider().gridCellColumns(9)
                quantileRow(presentation.pooled)
                if let balanced = presentation.trainBalanced {
                    quantileRow(balanced)
                }
            }
        }
    }

    private var perTrainSection: some View {
        sectionCard("Per-train valid ISIs + key quantiles") {
            Grid(alignment: .leading, horizontalSpacing: 14, verticalSpacing: 6) {
                quantileHeaderRow
                Divider().gridCellColumns(9)
                ForEach(presentation.perTrain, id: \.trainID) { row in
                    quantileRow(row)
                }
            }
        }
    }

    private var intervalSection: some View {
        sectionCard("D3 dataset interval priors") {
            if presentation.datasetIntervals.isEmpty {
                Text("No dataset-scope burst/tonic/pause priors derived.")
                    .foregroundStyle(.secondary)
            } else {
                VStack(alignment: .leading, spacing: 10) {
                    Text("core = central identity band (e.g. tonic q25–q75);  acc = wider acceptance / membership band;  bridge = burst extension.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    ForEach(presentation.datasetIntervals, id: \.self) { interval in
                        intervalRow(interval)
                    }
                }
            }
        }
    }

    // MARK: Rows

    private var quantileHeaderRow: some View {
        GridRow {
            cell("Scope", bold: true)
            cell("n", bold: true)
            cell("min", bold: true); cell("q10", bold: true); cell("q25", bold: true)
            cell("q50", bold: true); cell("q75", bold: true); cell("q90", bold: true); cell("max", bold: true)
        }
    }

    private func quantileRow(_ row: ISIDistributionQuantileRow) -> some View {
        GridRow {
            cell(row.label)
            cell("\(row.validISICount)")
            cell(ms(row.minSec)); cell(ms(row.q10Sec)); cell(ms(row.q25Sec))
            cell(ms(row.q50Sec)); cell(ms(row.q75Sec)); cell(ms(row.q90Sec)); cell(ms(row.maxSec))
        }
    }

    private func intervalRow(_ interval: ISIModeIntervalRow) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 10) {
            Text(familyName(interval.family))
                .font(.body.weight(.semibold))
                .foregroundStyle(familyColor(interval.family))
                .frame(width: 64, alignment: .leading)

            VStack(alignment: .leading, spacing: 2) {
                // Core (identity) interval.
                Text("core  [\(ms(interval.lowerSec)) – \(ms(interval.upperSec)) ms]")
                    .monospacedDigit()
                // Acceptance (wider membership) interval, shown only when it differs from the core.
                if interval.acceptanceLowerSec != nil || interval.acceptanceUpperSec != nil {
                    Text("acc.  [\(ms(interval.acceptanceLowerSec ?? interval.lowerSec)) – \(ms(interval.acceptanceUpperSec ?? interval.upperSec)) ms]")
                        .monospacedDigit()
                        .foregroundStyle(.secondary)
                }
                // Burst bridge/extension upper.
                if let bridge = interval.bridgeUpperSec {
                    Text("bridge → \(ms(bridge)) ms")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            Spacer(minLength: 8)

            badge(interval.scope.rawValue, tint: .indigo)
            badge(interval.provenanceOrigin.rawValue, tint: .purple)
            if interval.mayPropagateToDataset { badge("propagate", tint: .green) }
            if !interval.maySelectFinalLabel { badge("no-select", tint: .gray) }
            if interval.isAuditOnly { badge("audit-only", tint: .gray) }
            if !interval.isValid { badge("invalid", tint: .red) }
        }
    }

    // MARK: Selected-train composition (UI-2C)

    private var selectedTrainControl: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 10) {
                Text("Overlay trains (stacked)")
                    .font(.callout.weight(.medium))
                Text("\(selectedDetails.count) of \(presentation.perTrainDetails.count) selected")
                    .font(.caption).foregroundStyle(.secondary)
                Spacer()
                Button("None") { selectedTrainIDs = [] }
                    .disabled(selectedTrainIDs.isEmpty)
                Button("All") { selectedTrainIDs = Set(presentation.perTrainDetails.map(\.trainID)) }
                    .disabled(selectedDetails.count == presentation.perTrainDetails.count)
                Button("Top \(min(topN, presentation.perTrainDetails.count))") { selectTopByISICount(topN) }
                    .disabled(presentation.perTrainDetails.count <= topN)
            }
            .buttonStyle(.bordered)
            .controlSize(.small)

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 180), spacing: 8)], alignment: .leading, spacing: 8) {
                ForEach(presentation.perTrainDetails, id: \.trainID) { detail in
                    trainToggleChip(detail)
                }
            }

            if selectedDetails.count > 1 {
                focusControl
            }
        }
    }

    /// UI-2D focus picker: choose ONE of the selected trains whose detailed priors are drawn on the
    /// chart (the stacked bars still show every selected train's composition). Only shown when more than
    /// one train is selected — with a single selection that train is already the focus.
    private var focusControl: some View {
        HStack(spacing: 8) {
            Text("Focus")
                .font(.callout.weight(.medium))
            Picker("Focus train", selection: focusSelection) {
                ForEach(selectedDetails, id: \.trainID) { detail in
                    Text(detail.trainName).tag(String?.some(detail.trainID))
                }
            }
            .labelsHidden()
            .frame(maxWidth: 260)
            if let focus = focusedDetail {
                HStack(spacing: 5) {
                    RoundedRectangle(cornerRadius: 2).fill(trainColor(focus.trainID)).frame(width: 12, height: 10)
                    Text("priors drawn on chart: \(focus.trainName)")
                        .font(.caption).foregroundStyle(.secondary)
                }
            }
            Spacer()
        }
    }

    private func selectTopByISICount(_ n: Int) {
        let top = presentation.perTrainDetails
            .sorted { $0.validISICount > $1.validISICount }
            .prefix(n)
            .map(\.trainID)
        selectedTrainIDs = Set(top)
    }

    private func trainToggleChip(_ detail: ISIDistributionTrainDetail) -> some View {
        let isOn = selectedTrainIDs.contains(detail.trainID)
        let color = trainColor(detail.trainID)
        return Button {
            if isOn { selectedTrainIDs.remove(detail.trainID) } else { selectedTrainIDs.insert(detail.trainID) }
        } label: {
            HStack(spacing: 6) {
                RoundedRectangle(cornerRadius: 2)
                    .fill(isOn ? color : Color.secondary.opacity(0.35))
                    .frame(width: 12, height: 12)
                Text(detail.trainName).lineLimit(1)
                Spacer(minLength: 4)
                Text("\(detail.validISICount)").font(.caption2).foregroundStyle(.secondary).monospacedDigit()
            }
            .padding(.horizontal, 8).padding(.vertical, 5)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(isOn ? color.opacity(0.14) : Color.secondary.opacity(0.06),
                        in: RoundedRectangle(cornerRadius: 6))
            .overlay(
                RoundedRectangle(cornerRadius: 6)
                    .stroke(isOn ? color.opacity(0.55) : Color.secondary.opacity(0.18), lineWidth: 1))
        }
        .buttonStyle(.plain)
    }

    // Priors option chosen: a COMPACT LIST of ALL selected trains' priors, each group prefixed with the
    // train's stack color. Simpler than a separate "focused train" control (no extra state), and the
    // color header maps each prior group directly to its stacked segment; the ScrollView absorbs length.
    private var selectedTrainPriorsSection: some View {
        sectionCard("Selected-train interval priors") {
            if selectedDetails.isEmpty {
                Text("Select one or more trains above to stack their contributions and list their train-local priors.")
                    .foregroundStyle(.secondary)
            } else {
                VStack(alignment: .leading, spacing: 14) {
                    Text("Train-local priors per selected train — the “trainLocal” badge distinguishes these from the dataset priors below. (All selected trains shown; deselect to shorten.)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    ForEach(selectedDetails, id: \.trainID) { detail in
                        VStack(alignment: .leading, spacing: 6) {
                            HStack(spacing: 6) {
                                RoundedRectangle(cornerRadius: 2).fill(trainColor(detail.trainID)).frame(width: 12, height: 12)
                                Text(detail.trainName).font(.subheadline.weight(.semibold))
                                Text("(\(detail.validISICount) valid ISIs)").font(.caption).foregroundStyle(.secondary)
                                if detail.trainID == focusedDetail?.trainID {
                                    badge("focus", tint: .accentColor)   // priors drawn on the chart
                                }
                            }
                            if detail.intervals.isEmpty {
                                Text("No train-local burst/tonic/pause priors derived.")
                                    .font(.caption).foregroundStyle(.secondary)
                            } else {
                                ForEach(detail.intervals, id: \.self) { interval in
                                    intervalRow(interval)
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // MARK: TSW-2 tonic structural candidates (debug-only; unwired)

    private var tswCandidatesSection: some View {
        sectionCard("TSW tonic structural candidates") {
            if selectedDetails.isEmpty {
                Text("Select one or more trains above to list their TSW-2 sequence-local tonic structural candidates (debug only; TSW is unwired — it does not affect detection).")
                    .foregroundStyle(.secondary)
            } else {
                VStack(alignment: .leading, spacing: 12) {
                    Text("Sequence-local tonic windows discovered from each train's ISI ORDER (TSW-2) — a different object from the D3 distribution bands below: D3 = ISI-magnitude priors, TSW = ordered-run structure. On the chart, the focus train's candidates appear as PURPLE ISI value ranges (min–max), not time spans; the sequence span is the ISI-index range shown here.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    ForEach(selectedDetails, id: \.trainID) { detail in
                        let rows = tswCandidates(for: detail.trainID)
                        let isFocus = detail.trainID == focusedDetail?.trainID
                        VStack(alignment: .leading, spacing: 6) {
                            HStack(spacing: 6) {
                                RoundedRectangle(cornerRadius: 2).fill(trainColor(detail.trainID)).frame(width: 12, height: 12)
                                Text(detail.trainName).font(.subheadline.weight(.semibold))
                                if isFocus { badge("focus", tint: .accentColor) }
                                Text("\(rows.count) candidate\(rows.count == 1 ? "" : "s")")
                                    .font(.caption).foregroundStyle(.secondary)
                            }
                            .padding(isFocus ? 4 : 0)
                            .background(isFocus ? Color.purple.opacity(0.08) : Color.clear,
                                        in: RoundedRectangle(cornerRadius: 5))
                            if rows.isEmpty {
                                Text("No TSW tonic structural candidate.")
                                    .font(.caption).foregroundStyle(.secondary)
                            } else {
                                ForEach(rows, id: \.self) { row in tswRow(row) }
                            }
                        }
                    }
                }
            }
        }
    }

    private func tswRow(_ row: TSWCandidateRow) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack(spacing: 8) {
                Text("ISI seq [\(row.startISIIndex)–\(row.endISIIndex)] · spikes [\(row.startSpikeIndex)–\(row.endSpikeIndex)] · \(row.isiCount) ISIs")
                    .font(.caption).monospacedDigit()
                badge(tswRouteLabel(row.route), tint: tswRouteTint(row.route))
                badge(row.source, tint: .purple)
                if row.outsideD3Acceptance { badge("outside D3 acceptance", tint: .orange) }
                if row.reviewRequired { badge("review", tint: .yellow) }
            }
            HStack(spacing: 8) {
                Text("value range \(ms(row.lowerSec))–\(ms(row.upperSec)) ms")
                    .font(.caption2).foregroundStyle(.purple).monospacedDigit()
                Text("CV \(num(row.cv)) · CV2 \(num(row.cv2)) · LV \(num(row.lv))")
                    .font(.caption2).foregroundStyle(.secondary).monospacedDigit()
                if let reason = row.boundaryReason {
                    Text("boundary: \(reason)").font(.caption2).foregroundStyle(.secondary)
                }
            }
        }
    }

    /// Short label + color for a TSW-2A family route (classic = green; HF = amber; review = orange;
    /// too-fast = gray). Debug-only; TSW is unwired.
    private func tswRouteLabel(_ route: String) -> String {
        switch route {
        case "classicTonic": return "classic tonic"
        case "highFrequencyTonic": return "HF tonic"
        case "highFrequencySpiking": return "HF spiking"
        case "possibleTonicReview": return "tonic? review"
        case "tooFastForClassicTonic": return "too fast"
        default: return route
        }
    }
    private func tswRouteTint(_ route: String) -> Color {
        switch route {
        case "classicTonic": return .green
        case "highFrequencyTonic", "highFrequencySpiking": return .orange
        case "possibleTonicReview": return .yellow
        case "tooFastForClassicTonic": return .gray
        default: return .gray
        }
    }

    // MARK: Chart (UI-2A bars + UI-2C stacked composition)

    private var chartSection: some View {
        sectionCard("Pooled ISI distribution (log ISI)") {
            if let histogram = presentation.histogram, histogram.totalCount > 0 {
                VStack(alignment: .leading, spacing: 8) {
                    chartLegend
                    Canvas { context, size in
                        drawFoundationChart(histogram: histogram, datasetIntervals: presentation.datasetIntervals,
                                            stacked: stackedTrains, focus: focusedDetail,
                                            tswFocus: focusedTSWCandidates, context: &context, size: size)
                    }
                    .frame(height: 240)
                    .background(Color(nsColor: .textBackgroundColor).opacity(0.6),
                                in: RoundedRectangle(cornerRadius: 6))
                }
            } else {
                Text("Not enough ISI data to plot a distribution.")
                    .foregroundStyle(.secondary)
            }
        }
    }

    private var chartLegend: some View {
        HStack(spacing: 14) {
            legendSwatch("burst", familyColor(.burst))
            legendSwatch("tonic", familyColor(.tonic))
            legendSwatch("pause", familyColor(.pause))
            Divider().frame(height: 12)
            Text("dark = core · light = acceptance · mid = bridge")
                .font(.caption2).foregroundStyle(.secondary)
            if !selectedDetails.isEmpty {
                Divider().frame(height: 12)
                Text("colored stack = selected-train contributions (stacked on the gray pooled bar; colors in list below)")
                    .font(.caption2).foregroundStyle(.secondary)
            }
            if let focus = focusedDetail {
                Divider().frame(height: 12)
                Text("dashed = focus “\(focus.trainName)” priors (core; tonic acc. band; burst bridge ▾)")
                    .font(.caption2).foregroundStyle(.secondary)
            }
            if !focusedTSWCandidates.isEmpty {
                Divider().frame(height: 12)
                legendSwatch("TSW tonic candidates", .purple)
                Text("(focus train; ISI value range — NOT a time span)")
                    .font(.caption2).foregroundStyle(.secondary)
            }
        }
    }

    private func legendSwatch(_ label: String, _ color: Color) -> some View {
        HStack(spacing: 4) {
            RoundedRectangle(cornerRadius: 2).fill(color.opacity(0.5)).frame(width: 12, height: 10)
            Text(label).font(.caption2)
        }
    }

    private func drawFoundationChart(histogram: ISIDistributionHistogram, datasetIntervals: [ISIModeIntervalRow],
                                     stacked: [(detail: ISIDistributionTrainDetail, color: Color)],
                                     focus: ISIDistributionTrainDetail?, tswFocus: [TSWCandidateRow],
                                     context: inout GraphicsContext, size: CGSize) {
        let plot = CGRect(x: 8, y: 8, width: size.width - 16, height: size.height - 30)
        guard plot.width > 8, plot.height > 8, histogram.maxSec > histogram.minSec else { return }
        let logMin = log10(histogram.minSec)
        let logSpan = max(1e-9, log10(histogram.maxSec) - logMin)

        func x(_ sec: Double) -> CGFloat {
            let clamped = min(max(sec, histogram.minSec), histogram.maxSec)
            return plot.minX + CGFloat((log10(clamped) - logMin) / logSpan) * plot.width
        }
        func yTop(_ count: Int) -> CGFloat {
            let frac = histogram.maxCount > 0 ? CGFloat(count) / CGFloat(histogram.maxCount) : 0
            return plot.maxY - frac * plot.height
        }

        // 1) DATASET interval bands behind the bars: acceptance (lightest) < bridge (mid) < core (darkest).
        for interval in datasetIntervals {
            let color = familyColor(interval.family)
            if interval.acceptanceLowerSec != nil || interval.acceptanceUpperSec != nil {
                let al = interval.acceptanceLowerSec ?? interval.lowerSec
                let au = interval.acceptanceUpperSec ?? interval.upperSec
                fillBand(&context, x(al), x(au), plot, color.opacity(0.10))
            }
            if let bridge = interval.bridgeUpperSec, bridge > interval.upperSec {
                fillBand(&context, x(interval.upperSec), x(bridge), plot, color.opacity(0.16))
            }
            fillBand(&context, x(interval.lowerSec), x(interval.upperSec), plot, color.opacity(0.26))
            verticalRule(&context, x(interval.lowerSec), plot, color.opacity(0.6))
            verticalRule(&context, x(interval.upperSec), plot, color.opacity(0.6))
        }

        // 2) pooled histogram bars (gray).
        for bin in histogram.bins where bin.count > 0 {
            let x0 = x(bin.lowerSec), x1 = x(bin.upperSec)
            let top = yTop(bin.count)
            let rect = CGRect(x: x0 + 0.5, y: top, width: max(1, x1 - x0 - 1), height: plot.maxY - top)
            context.fill(Path(rect), with: .color(Color(nsColor: .labelColor).opacity(0.55)))
        }

        // 3) SELECTED-train STACKED composition (UI-2C): in each bin, stack each selected train's share
        // from the baseline up, on the SAME y-scale as the pooled bar. Segments sum to the trains'
        // summed contribution (≤ the gray pooled bar, which stays visible above for unselected mass);
        // stable perTrainDetails order → stable colors + stacking positions. NOT translucent overlays.
        let validStacks = stacked.filter { $0.detail.histogramCounts.count == histogram.bins.count }
        if !validStacks.isEmpty {
            for (index, bin) in histogram.bins.enumerated() {
                let barX = x(bin.lowerSec) + 0.5, barW = max(1, x(bin.upperSec) - x(bin.lowerSec) - 1)
                var baseline = plot.maxY
                for entry in validStacks {
                    let count = entry.detail.histogramCounts[index]
                    guard count > 0, histogram.maxCount > 0 else { continue }
                    let segHeight = CGFloat(count) / CGFloat(histogram.maxCount) * plot.height
                    let top = baseline - segHeight
                    context.fill(Path(CGRect(x: barX, y: top, width: barW, height: segHeight)),
                                 with: .color(entry.color.opacity(0.9)))
                    baseline = top
                }
            }
        }
        // 3b) FOCUS train (UI-2D): draw ONE focused train's train-local priors in detail — regardless of
        // how many trains are stacked — so boundaries stay legible without per-train clutter:
        //   • core dashed rules (every family)
        //   • tonic ACCEPTANCE band: faint fill + dashed edges (distinct from the dataset solid band)
        //   • burst BRIDGE marker: dashed rule + a small triangle at the top.
        if let focus {
            for interval in focus.intervals {
                let color = familyColor(interval.family)
                if interval.family == .tonic,
                   interval.acceptanceLowerSec != nil || interval.acceptanceUpperSec != nil {
                    let al = interval.acceptanceLowerSec ?? interval.lowerSec
                    let au = interval.acceptanceUpperSec ?? interval.upperSec
                    fillBand(&context, x(al), x(au), plot, color.opacity(0.07))
                    dashedRule(&context, x(al), plot, color.opacity(0.5))
                    dashedRule(&context, x(au), plot, color.opacity(0.5))
                }
                dashedRule(&context, x(interval.lowerSec), plot, color.opacity(0.95))
                dashedRule(&context, x(interval.upperSec), plot, color.opacity(0.95))
                if interval.family == .burst, let bridge = interval.bridgeUpperSec, bridge > interval.upperSec {
                    dashedRule(&context, x(bridge), plot, color.opacity(0.6))
                    let bx = x(bridge), s: CGFloat = 4
                    var marker = Path()
                    marker.move(to: CGPoint(x: bx, y: plot.minY + s))
                    marker.addLine(to: CGPoint(x: bx - s, y: plot.minY))
                    marker.addLine(to: CGPoint(x: bx + s, y: plot.minY))
                    marker.closeSubpath()
                    context.fill(marker, with: .color(color))
                }
            }
        }
        // 3c) TSW candidates (focus train only) — purple translucent bands at each candidate's ISI VALUE
        // range [min, max] with dashed purple edges. This is a MAGNITUDE range on the log-ISI axis, NOT a
        // time-span overlay; the sequence span (ISI indices) is shown in the list below. Distinct from the
        // green D3 tonic band so the two objects are not confused.
        for row in tswFocus {
            guard let lo = row.lowerSec, let hi = row.upperSec, hi >= lo else { continue }
            fillBand(&context, x(lo), x(hi), plot, Color.purple.opacity(0.10))
            dashedRule(&context, x(lo), plot, Color.purple.opacity(0.8))
            dashedRule(&context, x(hi), plot, Color.purple.opacity(0.8))
        }

        // 4) x baseline + log decade ticks / labels.
        context.stroke(Path { $0.move(to: CGPoint(x: plot.minX, y: plot.maxY)); $0.addLine(to: CGPoint(x: plot.maxX, y: plot.maxY)) },
                       with: .color(.secondary.opacity(0.5)), lineWidth: 1)
        for decade in decadeTicks(minSec: histogram.minSec, maxSec: histogram.maxSec) {
            let tx = x(decade)
            context.stroke(Path { $0.move(to: CGPoint(x: tx, y: plot.minY)); $0.addLine(to: CGPoint(x: tx, y: plot.maxY)) },
                           with: .color(.secondary.opacity(0.15)), lineWidth: 1)
            var label = context.resolve(Text(decadeLabel(decade)).font(.caption2))
            label.shading = .color(.secondary)
            context.draw(label, at: CGPoint(x: tx, y: plot.maxY + 11), anchor: .center)
        }
    }

    private func fillBand(_ context: inout GraphicsContext, _ x0: CGFloat, _ x1: CGFloat, _ plot: CGRect, _ color: Color) {
        let rect = CGRect(x: min(x0, x1), y: plot.minY, width: abs(x1 - x0), height: plot.height)
        context.fill(Path(rect), with: .color(color))
    }

    private func verticalRule(_ context: inout GraphicsContext, _ x: CGFloat, _ plot: CGRect, _ color: Color) {
        context.stroke(Path { $0.move(to: CGPoint(x: x, y: plot.minY)); $0.addLine(to: CGPoint(x: x, y: plot.maxY)) },
                       with: .color(color), lineWidth: 1)
    }

    private func dashedRule(_ context: inout GraphicsContext, _ x: CGFloat, _ plot: CGRect, _ color: Color) {
        context.stroke(Path { $0.move(to: CGPoint(x: x, y: plot.minY)); $0.addLine(to: CGPoint(x: x, y: plot.maxY)) },
                       with: .color(color), style: StrokeStyle(lineWidth: 1.5, dash: [4, 3]))
    }

    private func decadeTicks(minSec: Double, maxSec: Double) -> [Double] {
        var ticks: [Double] = []
        var decade = pow(10, (log10(minSec)).rounded(.down))
        while decade <= maxSec * 1.0000001 {
            if decade >= minSec { ticks.append(decade) }
            decade *= 10
        }
        return ticks
    }

    private func decadeLabel(_ sec: Double) -> String {
        sec >= 1 ? "\(Int(sec.rounded()))s" : "\(Int((sec * 1000).rounded()))ms"
    }

    private var emptyState: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("No valid ISI data")
                .font(.headline)
            Text("Load a dataset (or run detection) to populate the distribution-first foundation.")
                .foregroundStyle(.secondary)
        }
        .padding(.vertical, 12)
    }

    // MARK: Building blocks

    private func sectionCard<Content: View>(_ title: String, @ViewBuilder _ content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title).font(.headline)
            content()
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 8))
    }

    private func cell(_ text: String, bold: Bool = false) -> some View {
        Text(text)
            .font(bold ? .caption.weight(.semibold) : .caption)
            .foregroundStyle(bold ? .secondary : .primary)
            .monospacedDigit()
    }

    private func metric(_ label: String, _ value: String) -> some View {
        HStack(spacing: 4) {
            Text(label + ":").foregroundStyle(.secondary)
            Text(value).fontWeight(.medium)
        }
    }

    private func badge(_ text: String, tint: Color) -> some View {
        Text(text)
            .font(.caption2.weight(.semibold))
            .padding(.horizontal, 7).padding(.vertical, 2)
            .background(tint.opacity(0.16), in: Capsule())
            .foregroundStyle(tint)
    }

    private func ms(_ sec: Double?) -> String {
        guard let sec else { return "—" }
        return String(format: "%.2f", sec * 1000)
    }

    /// Format a dimensionless metric (CV/CV2/LV) for compact display.
    private func num(_ value: Double?) -> String {
        guard let value else { return "—" }
        return String(format: "%.2f", value)
    }

    private func familyName(_ family: ISIPatternFamily) -> String {
        switch family {
        case .burst: return "Burst"
        case .tonic: return "Tonic"
        case .pause: return "Pause"
        case .unknown: return "Unknown"
        }
    }

    private func familyColor(_ family: ISIPatternFamily) -> Color {
        // Match existing app/raster color semantics.
        switch family {
        case .burst: return .orange
        case .tonic: return .green
        case .pause: return .blue
        case .unknown: return .gray
        }
    }
}

// MARK: - Preview

private func isiDistributionFoundationPreviewDataset() -> SpikeDataset {
    func train(_ name: String, _ isis: [Double]) -> SpikeTrain {
        var ts = [0.0]
        for isi in isis { ts.append((ts.last ?? 0) + isi) }
        return SpikeTrain(name: name, timestampsSec: ts)
    }
    let burst = [0.003, 0.0032, 0.0035, 0.003, 0.0033]
    let tonic = [0.040, 0.052, 0.045, 0.058, 0.048, 0.055, 0.043, 0.050, 0.047, 0.053]
    // Large-ISI tail so D3 derives a pause interval too (a clear upper gap above the tonic mode).
    let pauseTail = [0.50, 0.60, 0.55, 0.52]
    return SpikeDataset(
        name: "preview", sourceDescription: "fixture",
        trains: [train("burst+tonic+pause", burst + tonic + pauseTail), train("tonic-only", tonic)])
}

#Preview("Distribution-first foundation (D1-D3)") {
    ISIDistributionFoundationView(
        dataset: isiDistributionFoundationPreviewDataset(),
        runDistribution: nil,
        minimumValidISISec: 0.001)
        .frame(width: 660, height: 760)
}
