test_that("visual semantics keep spike ticks uniform and strips pattern-coded", {
  expect_equal(base_spike_color("trainA", "neutral"), "#000000")
  expect_equal(base_spike_color("trainA", "by_train"), "#000000")
  st_manual <- pattern_style("burst", source = "manual", mode = "source_priority")
  st_auto <- pattern_style("burst", source = "auto", mode = "source_priority")
  st_review <- pattern_style("possible_burst", source = "review", mode = "source_priority")
  expect_equal(st_manual$color, "#000000")
  expect_equal(st_auto$color, "#000000")
  expect_equal(st_review$color, "#000000")
  expect_equal(st_review$dash, "solid")
  expect_equal(raster_label_line_width(), 1.0)
  strip <- pattern_strip_style("burst", source = "manual")
  expect_equal(strip$color, "#FB8DB8")
  strip2 <- pattern_strip_style("burst", source = "auto")
  expect_equal(strip2$color, "#CF57D5")
  expect_equal(pattern_strip_line_width(), 4.5)
})

test_that("UI pattern labels stay neutral while boxes carry pattern color", {
  label <- getFromNamespace("stpd_ui_pattern_label", "SpikeTrainPatternDetector")("Burst seed", "burst")
  label_text <- paste(as.character(label), collapse = "")
  expect_true(grepl("pattern-text-label", label_text, fixed = TRUE))
  expect_false(grepl("#FB8DB8", label_text, fixed = TRUE))

  contract_ui <- getFromNamespace("stpd_contract_ui_controls", "SpikeTrainPatternDetector")(ui_level = "basic")
  contract_text <- paste(as.character(contract_ui), collapse = "")
  expect_true(grepl("schema-section-box", contract_text, fixed = TRUE))
  expect_true(grepl("border-color:#FB8DB8", contract_text, fixed = TRUE))
})
