import Foundation
import Testing
@testable import STPDCore   // exercises the internal `diffusionProbability` kernel helper directly

// NM-3C: R-compatible Neural Manifold PHATE fallback (`diffusion_potential_mds`) on `matrix.scaled`. Reference
// coordinates and kernel bandwidth ε are generated by R 4.6.0 itself (`stpd_diffusion_probability` + matrix
// power + `-log` potential + `stats::cmdscale(dist(potential), add = TRUE)`) for the deterministic 6×4 input
// below. R reports the Cailliez additive constant as ≈1e-16 (the diffusion-potential distance is already
// Euclidean), confirming classical MDS reproduces R's coordinates up to axis sign/reflection.

private func matrix(scaled: [[Double]]) -> NeuralPopulationMatrix {
    let nBins = scaled.count
    let nNeurons = scaled.first?.count ?? 0
    var bins: [NeuralPopulationBin] = []
    for i in 0..<nBins {
        let start = Double(i)
        bins.append(NeuralPopulationBin(binID: i + 1, startSec: start, endSec: start + 1,
                                        midSec: start + 0.5, widthSec: 1))
    }
    let ids = (0..<nNeurons).map { "n\($0)" }
    return NeuralPopulationMatrix(
        bins: bins, trainIDs: ids, trainNames: ids,
        counts: scaled, rates: scaled, signal: scaled, scaled: scaled,
        transform: .sqrtCount, scaling: .zscore, timeOrigin: .raw,
        binSec: 1, smoothingSigmaBins: 0, windowStartSec: 0, windowEndSec: Double(nBins)
    )
}

/// Deterministic 6 bins × 4 neurons input: `X[i][j] = sin(0.5·(i+1) + (j+1)) + 0.1·(i+1)·(j+1)` (1-based),
/// hard-coded to the exact values R embedded.
private let referenceMatrix: [[Double]] = [
    [1.0974949866, 0.7984721441, -0.0507832277, -0.5775301177],
    [1.1092974268, 0.5411200081, -0.1568024953, -0.1589242747],
    [0.8984721441, 0.2492167723, -0.0775301177, 0.4944596744],
    [0.5411200081, 0.0431975047, 0.2410757253, 1.3205845018],
    [0.1492167723, 0.0224698823, 0.7944596744, 2.2151199881],
    [-0.1568024953, 0.2410757253, 1.5205845018, 3.0569865987],
]

/// R `stats::cmdscale(..., add = TRUE)` coordinates (rows = bins, cols = PHATE1..3).
private let referenceCoords: [[Double]] = [
    [-1.2432342130, 0.1896174059, 0.0056572920],
    [-1.0618300418, 0.0851285800, -0.0008547386],
    [-0.6450878768, -0.1081178047, -0.0080181114],
    [0.0921591132, -0.2662876679, -0.0014045159],
    [1.0356930873, -0.1262597771, 0.0093265854],
    [1.8222999311, 0.2259192637, -0.0047065116],
]
private let referenceEpsilon = 3.625920786722

/// A deterministic `count × width` activity matrix (no RNG) for the sampling tests.
private func deterministicRows(count: Int, width: Int) -> [[Double]] {
    var rows: [[Double]] = []
    for i in 0..<count {
        var row: [Double] = []
        for j in 0..<width {
            let phase: Double = 0.3 * Double(i) + Double(j)
            let drift: Double = 0.05 * Double(i)
            row.append(Foundation.sin(phase) + drift)
        }
        rows.append(row)
    }
    return rows
}

/// `min_{s ∈ {+1,-1}} max_i |swift_i − s·ref_i|` — classical MDS is unique only up to per-axis sign/reflection.
private func columnMatchesUpToSign(_ swift: [Double], _ ref: [Double], tol: Double) -> Bool {
    let plus = zip(swift, ref).map { abs($0 - $1) }.max() ?? 0
    let minus = zip(swift, ref).map { abs($0 + $1) }.max() ?? 0
    return Swift.min(plus, minus) <= tol
}

// MARK: - R parity

@Test
func neuralPhateMatchesRReferenceCoordinatesUpToSign() throws {
    let result = try NeuralPopulationPhate.run(
        matrix: matrix(scaled: referenceMatrix), neighborCount: 3, diffusionTime: 3, maxPoints: 1200
    )
    #expect(result.points.count == 6)
    for axis in 0..<3 {
        let swiftColumn = result.points.map { [$0.nm1, $0.nm2, $0.nm3][axis] }
        let refColumn = referenceCoords.map { $0[axis] }
        #expect(
            columnMatchesUpToSign(swiftColumn, refColumn, tol: 1e-6),
            "PHATE axis \(axis + 1) does not match R up to sign: \(swiftColumn) vs \(refColumn)"
        )
    }
}

@Test
func neuralPhateKernelBandwidthMatchesR() {
    let kernel = NeuralPopulationPhate.diffusionProbability(referenceMatrix, neighborCount: 3)
    #expect(abs(kernel.epsilon - referenceEpsilon) < 1e-6)
    #expect(kernel.effectiveK == 3)
    // P is row-stochastic (each row of the diffusion operator sums to 1).
    for row in kernel.p {
        #expect(abs(row.reduce(0, +) - 1) < 1e-9)
    }
}

// MARK: - Shape / bin context

@Test
func neuralPhateEmbeddedShapeAndDiagnostics() throws {
    let result = try NeuralPopulationPhate.run(
        matrix: matrix(scaled: referenceMatrix), neighborCount: 3, diffusionTime: 3, maxPoints: 1200
    )
    // One score per embedded bin, bin context preserved in order, NM1–NM3 all finite (R take3 pads 0).
    #expect(result.points.map { $0.bin.binID } == [1, 2, 3, 4, 5, 6])
    for point in result.points {
        #expect(point.nm1.isFinite && point.nm2.isFinite && point.nm3.isFinite)
    }
    let d = result.diagnostics
    #expect(d.inputBinCount == 6)
    #expect(d.sampledCount == 6)
    #expect(d.embeddedCount == 6)
    #expect(d.sampled == false)
    #expect(d.neighborCount == 3)
    #expect(d.diffusionTime == 3)
    #expect(d.featureNeuronCount == 4)
    #expect(d.backend == "diffusion_potential_mds")
    #expect(d.methodLabel == "PHATE")
}

@Test
func neuralPhateIsDeterministic() throws {
    let a = try NeuralPopulationPhate.run(matrix: matrix(scaled: referenceMatrix), neighborCount: 3, diffusionTime: 3)
    let b = try NeuralPopulationPhate.run(matrix: matrix(scaled: referenceMatrix), neighborCount: 3, diffusionTime: 3)
    #expect(a.points == b.points)
}

@Test
func neuralPhateDiffusionTimeChangesEmbedding() throws {
    let t1 = try NeuralPopulationPhate.run(matrix: matrix(scaled: referenceMatrix), neighborCount: 3, diffusionTime: 1)
    let t3 = try NeuralPopulationPhate.run(matrix: matrix(scaled: referenceMatrix), neighborCount: 3, diffusionTime: 3)
    let differs = zip(t1.points, t3.points).contains { abs($0.nm1 - $1.nm1) > 1e-9 }
    #expect(differs, "Different diffusion times should yield different embeddings")
}

// MARK: - Guards

@Test
func neuralPhateRejectsTooFewBins() {
    let small = Array(referenceMatrix.prefix(4))   // 4 < 5
    #expect(throws: NeuralPopulationPhateError.tooFewBins) {
        _ = try NeuralPopulationPhate.run(matrix: matrix(scaled: small))
    }
}

@Test
func neuralPhateRejectsTooFewNeurons() {
    let oneColumn = referenceMatrix.map { [$0[0]] }   // 6 bins × 1 neuron
    #expect(throws: NeuralPopulationPhateError.tooFewNeurons) {
        _ = try NeuralPopulationPhate.run(matrix: matrix(scaled: oneColumn))
    }
}

@Test
func neuralPhateKeepsConstantNeuronColumnsLikeR() throws {
    // R checks ncol(X) >= 2 and does not drop constant columns; a constant column contributes 0 distance.
    let scaled = (0..<6).map { i in [Double(i), 1.0] }
    let result = try NeuralPopulationPhate.run(matrix: matrix(scaled: scaled), neighborCount: 3)
    #expect(result.points.count == 6)
    #expect(result.diagnostics.featureNeuronCount == 2)
}

// MARK: - max_points sampling (shared R rule)

@Test
func neuralPhateMaxPointsCapsEmbeddedBinsWithEvenSampling() throws {
    let rows = deterministicRows(count: 30, width: 3)
    let result = try NeuralPopulationPhate.run(matrix: matrix(scaled: rows), neighborCount: 5, diffusionTime: 3, maxPoints: 20)
    #expect(result.diagnostics.sampled)
    #expect(result.diagnostics.sampledCount == 20)
    #expect(result.diagnostics.embeddedCount == 20)
    #expect(result.points.count == 20)
    // Embedded bin IDs are the even-spaced sample (1-based binIDs of the shared sampler).
    let expected = ISIStateSpaceIsomap.sampleIndices(count: 30, maxPoints: 20).map { $0 + 1 }
    #expect(result.points.map { $0.bin.binID } == expected)
}

@Test
func neuralPhateMaxPointsFloorsToTwentyLikeR() throws {
    let rows = deterministicRows(count: 30, width: 3)
    // maxPoints below R's floor of 20 is clamped to 20.
    let result = try NeuralPopulationPhate.run(matrix: matrix(scaled: rows), neighborCount: 5, diffusionTime: 3, maxPoints: 5)
    #expect(result.points.count == 20)
    #expect(result.diagnostics.embeddedCount == 20)
}
