import Foundation
import Testing
@testable import STPDCore   // exercises the internal maxFactorCount / rankDropColumns / sortLoadings helpers

// NM-3D: R-compatible Neural Manifold Factor Analysis (and GPFA-style smoothed variant) on `matrix.scaled`.
// Reference loadings / uniquenesses / scores are generated by R 4.6.0 `stats::factanal(X, factors = 3,
// scores = "regression", rotation = "none", control = list(nstart = 20))` for the deterministic 40×6 input
// below. Comparison is up to per-factor sign (classical FA sign ambiguity, fixed by factanal's sortLoadings).

private func matrix(scaled: [[Double]]) -> NeuralPopulationMatrix {
    let nBins = scaled.count
    let nNeurons = scaled.first?.count ?? 0
    var bins: [NeuralPopulationBin] = []
    for i in 0..<nBins {
        let start = Double(i)
        bins.append(NeuralPopulationBin(binID: i + 1, startSec: start, endSec: start + 1,
                                        midSec: start + 0.5, widthSec: 1))
    }
    let ids = (0..<nNeurons).map { "n\($0)" }
    return NeuralPopulationMatrix(
        bins: bins, trainIDs: ids, trainNames: ids,
        counts: scaled, rates: scaled, signal: scaled, scaled: scaled,
        transform: .sqrtCount, scaling: .zscore, timeOrigin: .raw,
        binSec: 1, smoothingSigmaBins: 0, windowStartSec: 0, windowEndSec: Double(nBins)
    )
}

/// Deterministic 40 bins × 6 trains fixture: `X[i][j] = sin(0.35·i + 0.6·j) + 0.6·cos(0.12·i·j) + 0.04·i − 0.5·j`
/// (1-based), hard-coded to the exact values R embedded.
private let referenceMatrix: [[Double]] = [
    [0.9491006863, 0.6225865491, -0.0615631150, -1.0461420543, -2.1717006027, -3.2321046866],
    [1.1263609703, 0.5584970414, -0.3704444184, -1.5343073459, -2.7324214882, -3.7579117115],
    [1.1784031227, 0.3491566344, -0.8097249692, -2.1052872875, -3.3048465112, -4.2114739265],
    [1.1014943805, 0.0196133635, -1.3201199182, -2.6571476816, -3.7340383032, -4.3785118621],
    [0.9066747217, -0.3921627000, -1.8334694241, -3.0884199304, -3.8932882869, -4.1415752057],
    [0.6184633177, -0.8394914689, -2.2811856469, -3.3171177051, -3.7238697321, -3.5401236932],
    [0.2719423377, -1.2721787000, -2.6027605805, -3.2962928014, -3.2542338033, -2.7580085707],
    [-0.0914291104, -1.6420922860, -2.7532785911, -3.0229749952, -2.5921027894, -2.0437115568],
    [-0.4287643002, -1.9084720653, -2.7090002114, -2.5386780079, -1.8919761833, -1.6015392696],
    [-0.7008624584, -2.0423594869, -2.4703224920, -1.9213772748, -1.3087778399, -1.5060201712],
    [-0.8768677896, -2.0296394029, -2.0617464628, -1.2706076810, -0.9529128424, -1.6800790764],
    [-0.9379103836, -1.8723520750, -1.5288536488, -0.6887193981, -0.8613213474, -1.9459837714],
    [-0.8792889712, -1.5881392101, -0.9326649991, -0.2620732761, -0.9934744814, -2.1222360182],
    [-0.7109323769, -1.2079087697, -0.3420808618, -0.0459010879, -1.2526318506, -2.1172604782],
    [-0.4560852747, -0.7720129439, 0.1746606705, -0.0557214286, -1.5240739469, -1.9729495002],
    [-0.1483791935, -0.3254069883, 0.5584473342, -0.2667786121, -1.7164156156, -1.8366804995],
    [0.1723544851, 0.0876270303, 0.7666276582, -0.6212741333, -1.7914184132, -1.8765677248],
    [0.4650202766, 0.4285618261, 0.7783064674, -1.0415578867, -1.7721435204, -2.1834220213],
    [0.6923430827, 0.6689121582, 0.5969429471, -1.4462822527, -1.7272282794, -2.7098537748],
    [0.8254834427, 0.7932299467, 0.2499279816, -1.7660372880, -1.7377087356, -3.2786658353],
    [0.8476225550, 0.8004703744, -0.2148075710, -1.9552667844, -1.8590936231, -3.6582049398],
    [0.7560810995, 0.7035923920, -0.7347333727, -1.9982293305, -2.0931046417, -3.6687967343],
    [0.5627138025, 0.5274722319, -1.2404720611, -1.9081827684, -2.3800303597, -3.2684686026],
    [0.2925308978, 0.3054124572, -1.6644018044, -1.7205066437, -2.6152189394, -2.5758286750],
    [-0.0192872076, 0.0746970438, -1.9490414671, -1.4817876512, -2.6844777235, -1.8184962604],
    [-0.3316207590, -0.1282452140, -2.0541778382, -1.2376887487, -2.5061540396, -1.2317963404],
    [-0.6023744661, -0.2724644187, -1.9618505354, -1.0225378697, -2.0649316356, -0.9565885087],
    [-0.7935727345, -0.3363279151, -1.6785761858, -0.8530003251, -1.4248973273, -0.9851715429],
    [-0.8759686273, -0.3101029492, -1.2345362417, -0.7270914975, -0.7163776738, -1.1801970250],
    [-0.8326076380, -0.1969727952, -0.6798297352, -0.6284159746, -0.1000255485, -1.3553736762],
    [-0.6609138984, -0.0123725429, -0.0782565728, -0.5342154089, 0.2804634641, -1.3763828442],
    [-0.3730454242, 0.2182589658, 0.5005966232, -0.4248796781, 0.3415588607, -1.2308881448],
    [0.0055252950, 0.4630168824, 0.9899856625, -0.2922421425, 0.0847809472, -1.0324828406],
    [0.4390340406, 0.6879028336, 1.3342820546, -0.1443157604, -0.4049081445, -0.9568794049],
    [0.8856853688, 0.8614730723, 1.4958641183, -0.0050491802, -0.9865153876, -1.1429162396],
    [1.3026353641, 0.9591685527, 1.4597716491, 0.0910320831, -1.5069294126, -1.6089480407],
    [1.6510936840, 0.9667722301, 1.2355478386, 0.1080947648, -1.8466423081, -2.2279041292],
    [1.9009275863, 0.8825468920, 0.8560415252, 0.0199045849, -1.9522501970, -2.7753150408],
    [2.0342111105, 0.7177705668, 0.3733202112, -0.1804349196, -1.8455004434, -3.0282923853],
    [2.0472905622, 0.4955859754, -0.1477972640, -0.4745744743, -1.6068900875, -2.8678384276],
]

/// R `fit$loadings` (6 × 3, after `sortLoadings`).
private let referenceLoadings: [[Double]] = [
    [0.8445616658, -0.5304094318, 0.0195583534],
    [0.8297790982, 0.0030197295, -0.0202652847],
    [0.8478119338, 0.5252122939, -0.0193811995],
    [0.4093017516, 0.7268851488, 0.3466826630],
    [0.0032119737, 0.8400576474, 0.2794283296],
    [-0.3114958171, 0.6976738659, 0.4679350100],
]
private let referenceUniqueness: [Double] = [
    0.0050000000, 0.3110468321, 0.0050000000, 0.1839211976, 0.2162126296, 0.1972583772,
]
private let referenceMeanUniqueness = 0.1530731728
/// R `fit$scores` rows 1–6 and 39–40 (n = 40).
private let referenceScoresHead: [[Double]] = [
    [0.6992840491, -0.3299570862, -0.3602616539],
    [0.6751341009, -0.7621372282, -0.7017739446],
    [0.5071883568, -1.1583638943, -1.0897886107],
    [0.2196157819, -1.4608104566, -1.3140493211],
    [-0.1490327961, -1.6240681695, -1.2331650803],
    [-0.5503527883, -1.6231142602, -0.8374703765],
]
private let referenceScoresTail: [[Double]] = [
    [1.6167873952, -1.0732127260, 1.4693620033],
    [1.3849296198, -1.4340666273, 2.0078720181],
]

/// The sign `s ∈ {+1,−1}` aligning a Swift factor column to its R reference (FA sign ambiguity).
private func columnSign(_ swift: [Double], _ ref: [Double]) -> Double {
    let plus = zip(swift, ref).map { abs($0 - $1) }.max() ?? 0
    let minus = zip(swift, ref).map { abs($0 + $1) }.max() ?? 0
    return plus <= minus ? 1 : -1
}

// MARK: - R parity

@Test
func neuralFactorMatchesRReferenceUpToSign() throws {
    let result = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: referenceMatrix), maxFactors: 3)
    #expect(result.diagnostics.factorCount == 3)
    #expect(result.loadings.count == 6)
    #expect(result.points.count == 40)

    // Loadings, per factor, up to sign; remember the sign to apply to the scores.
    var factorSign = [1.0, 1.0, 1.0]
    for c in 0..<3 {
        let swiftColumn = result.loadings.map { [$0.f1 ?? .nan, $0.f2 ?? .nan, $0.f3 ?? .nan][c] }
        let refColumn = referenceLoadings.map { $0[c] }
        let sign = columnSign(swiftColumn, refColumn)
        factorSign[c] = sign
        let maxDiff = zip(swiftColumn, refColumn).map { abs($0 - sign * $1) }.max() ?? 0
        #expect(maxDiff < 2e-3, "loadings factor \(c + 1) max diff \(maxDiff)")
    }

    // Uniquenesses (sign-independent).
    let swiftUniqueness = result.loadings.map { $0.uniqueness }
    let uniqDiff = zip(swiftUniqueness, referenceUniqueness).map { abs($0 - $1) }.max() ?? 0
    #expect(uniqDiff < 2e-3, "uniqueness max diff \(uniqDiff)")
    #expect(abs(result.diagnostics.meanUniqueness - referenceMeanUniqueness) < 2e-3)
    // Heywood boundary preserved (R clamps uniqueness at 0.005).
    #expect(swiftUniqueness.allSatisfy { $0 >= 0.005 - 1e-9 })

    // Scores (head rows 0–5, tail rows 38–39), each factor with the SAME sign as its loadings column.
    func checkScores(_ swiftRows: [[Double]], _ refRows: [[Double]]) {
        for (swiftRow, refRow) in zip(swiftRows, refRows) {
            for c in 0..<3 {
                #expect(abs(swiftRow[c] - factorSign[c] * refRow[c]) < 5e-3,
                        "score factor \(c + 1) diff \(abs(swiftRow[c] - factorSign[c] * refRow[c]))")
            }
        }
    }
    let head = result.points.prefix(6).map { [$0.nm1, $0.nm2, $0.nm3] }
    let tail = result.points.suffix(2).map { [$0.nm1, $0.nm2, $0.nm3] }
    checkScores(Array(head), referenceScoresHead)
    checkScores(Array(tail), referenceScoresTail)
}

// MARK: - Shape / no sampling

@Test
func neuralFactorEmbedsEveryBinNoSampling() throws {
    // 50 bins (far above any sampled-method cap); FA must embed all of them 1:1 in order — there is no
    // `maxPoints` parameter on `run`.
    let rows = referenceMatrix + referenceMatrix.prefix(10)   // 50 × 6, still well-conditioned
    let result = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: rows), maxFactors: 3)
    #expect(result.points.count == 50)
    #expect(result.points.map { $0.bin.binID } == Array(1...50))
    #expect(result.diagnostics.inputBinCount == 50)
}

@Test
func neuralFactorIsDeterministic() throws {
    let a = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: referenceMatrix))
    let b = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: referenceMatrix))
    #expect(a.points == b.points)
    #expect(a.loadings == b.loadings)
}

@Test
func neuralFactorDiagnosticsAndLabels() throws {
    let fa = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: referenceMatrix))
    #expect(fa.diagnostics.methodLabel == "FA")
    #expect(fa.diagnostics.smoothed == false)
    #expect(fa.diagnostics.keptFeatureCount == 6)
    #expect(fa.diagnostics.droppedFeatureCount == 0)
    #expect(fa.loadings.allSatisfy { $0.f1 != nil && $0.f2 != nil && $0.f3 != nil })
}

// MARK: - GPFA-style (smoothed)

@Test
func neuralFactorGPFASmoothingChangesEmbeddingAndLabel() throws {
    let fa = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: referenceMatrix), smoothingSigmaBins: nil)
    let gpfa = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: referenceMatrix), smoothingSigmaBins: 2)
    #expect(gpfa.diagnostics.smoothed == true)
    #expect(gpfa.diagnostics.methodLabel == "GPFA-style smooth FA")
    let differs = zip(fa.points, gpfa.points).contains { abs($0.nm1 - $1.nm1) > 1e-6 || abs($0.nm2 - $1.nm2) > 1e-6 }
    #expect(differs, "Gaussian smoothing should change the GPFA-style embedding")
}

// MARK: - Factor-count rule (mirror of stpd_state_trajectory_max_fa_factors)

@Test
func neuralFactorMaxFactorCountMatchesR() {
    #expect(NeuralPopulationFactorAnalysis.maxFactorCount(featureCount: 2, maxFactors: 3) == 0)
    #expect(NeuralPopulationFactorAnalysis.maxFactorCount(featureCount: 3, maxFactors: 3) == 1)
    #expect(NeuralPopulationFactorAnalysis.maxFactorCount(featureCount: 4, maxFactors: 3) == 1)
    #expect(NeuralPopulationFactorAnalysis.maxFactorCount(featureCount: 5, maxFactors: 3) == 2)
    #expect(NeuralPopulationFactorAnalysis.maxFactorCount(featureCount: 6, maxFactors: 3) == 3)
    #expect(NeuralPopulationFactorAnalysis.maxFactorCount(featureCount: 10, maxFactors: 3) == 3)
}

// MARK: - Guards

@Test
func neuralFactorRejectsTooFewBins() {
    let small = Array(referenceMatrix.prefix(2))   // 2 < 3
    #expect(throws: NeuralPopulationFactorError.tooFewBins) {
        _ = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: small))
    }
}

@Test
func neuralFactorRejectsTooFewFeatures() {
    let twoColumns = referenceMatrix.map { Array($0.prefix(2)) }   // 40 × 2 → p < 3
    #expect(throws: NeuralPopulationFactorError.tooFewFeatures) {
        _ = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: twoColumns))
    }
}

@Test
func neuralFactorRejectsNotIdentified() {
    // 3 bins × 3 independent columns → factorCount 1 but nrow 3 < 1 + 3.
    let tiny: [[Double]] = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    #expect(throws: NeuralPopulationFactorError.notIdentified) {
        _ = try NeuralPopulationFactorAnalysis.run(matrix: matrix(scaled: tiny))
    }
}
