import Foundation

/// Exact, display-only copy for the scientific-import review workflow.
///
/// Keeping the page vocabulary in one catalog makes coverage auditable and prevents scientific
/// identifiers, filenames, worksheet names, and source values from being translated accidentally.
enum STPDScientificImportLocalization {
    static func text(_ source: String, language: STPDLanguage) -> String? {
        switch language {
        case .zh: source
        case .en: english[source]
        case .ru: russian[source]
        }
    }

    static var sourceKeys: Set<String> { Set(english.keys).union(russian.keys) }

    static let english: [String: String] = [
        "数据集含义": "Dataset meaning",
        "列与分组": "Columns & groups",
        "事件与属性": "Events & attributes",
        "审核": "Review",
        "绑定数据源": "Bind data source",
        "阶段 A 只记录确切文件、工作表和表头规则，不作任何科学假设。": "Stage A records only the exact file, worksheet, and header rule; it makes no scientific assumptions.",
        "正在读取受限的数据源快照…": "Reading the bounded data-source snapshot…",
        "数据源尚未绑定": "Data source not bound",
        "请关闭此审核并选择受支持的 CSV 或 XLSX 文件。": "Close this review and select a supported CSV or XLSX file.",
        "尚未选择数据源": "No data source selected",
        "请从工具栏或“文件”菜单选择“导入数据”。": "Choose Import Data from the toolbar or File menu.",
        "确认数据集含义": "Confirm dataset meaning",
        "这些决定适用于整个文件；不会根据表头或时间戳数值大小推断任何含义。": "These decisions apply to the entire file; no meaning is inferred from headers or timestamp magnitudes.",
        "时间戳合同": "Timestamp contract",
        "数据源时间戳单位": "Source timestamp unit",
        "未确定": "Not determined",
        "秒（s）": "Seconds (s)",
        "毫秒（ms）": "Milliseconds (ms)",
        "接受的时间戳必须能精确映射为有符号整数微秒。以秒显示时保留 6 位小数，以毫秒显示时保留 3 位；导入器绝不会静默舍入。记录经过时间为负值时会阻止导入；只有明确确认事件原点后，有符号的事件相对时间戳才可能有效。": "Accepted timestamps must map exactly to signed integer microseconds. Seconds retain 6 decimal places and milliseconds retain 3; the importer never rounds silently. Negative recording-elapsed time blocks import; signed event-relative timestamps may be valid only after an event origin is explicitly confirmed.",
        "此文件所表示的活动类型": "Activity represented by this file",
        "活动模式": "Activity mode",
        "更改活动模式会清除每个 spike 列的重复时间戳决定，因为相同时间戳在不同模式下具有不同科学含义。请重新逐项明确确认。": "Changing activity mode clears the duplicate-timestamp decision for every spike column because identical timestamps have different scientific meanings across modes. Confirm each decision again.",
        "此文件的记录片段": "Recording segment in this file",
        "本次导入整体视为一个记录片段，所有 spike train 和事件组均属于该片段。共享同一片段并不意味着时钟或原点不同的分组可以直接比较。": "This import is treated as one recording segment containing all spike trains and event groups. Sharing a segment does not make groups with different clocks or origins directly comparable.",
        "记录片段 ID": "Recording-segment ID",
        "输入并确认稳定的片段标识符": "Enter and confirm a stable segment identifier",
        "这是承载科学身份的稳定记录片段标识符。界面默认填入导入文件名（不含 .csv/.xlsx），您可以直接编辑或从外部复制粘贴；最终以确认时界面中的完整文字为准。": "This stable recording-segment identifier carries scientific identity. It defaults to the imported filename without .csv/.xlsx and can be edited or pasted; the complete text present at confirmation is authoritative.",
        "文件名只提供可编辑的初始建议，不会被静默清理或改写；非空但无效的标识符会被拒绝。CSV 与 XLSX 扩展名不进入该建议。": "The filename is only an editable initial suggestion and is never silently cleaned or rewritten; a non-empty invalid identifier is rejected. CSV and XLSX extensions are excluded from the suggestion.",
        "记录组织方式": "Recording organization",
        "连续记录，无试次": "Continuous recording, no trials",
        "按试次组织": "Trialized",
        "导入片段内的 spike-train 覆盖情况": "Spike-train coverage within imported excerpt",
        "所有纳入的 spike-train 数据流在整个导入片段内均持续可观察且有效": "All included spike-train streams are continuously observable and valid throughout the imported excerpt",
        "至少一条纳入的 spike-train 数据流在导入片段内并非全程可观察或有效": "At least one included spike-train stream is not observable or valid throughout the imported excerpt",
        "完整覆盖表示每条纳入的 spike-train 数据流在整个片段内持续可观察且有效；并不要求片段起止边缘必须出现 spike、数据流必须非空，也不构成单单位分离质量的证明。": "Full coverage means every included spike-train stream is continuously observable and valid throughout the excerpt. It does not require spikes at either boundary, require a non-empty stream, or prove single-unit isolation quality.",
        "我确认确切的记录起止时间未知或无法获得": "I confirm that exact recording start and end times are unknown or unavailable",
        "重复的刺激或奖赏事件不会自动建立试次。连续数据可能只是较长记录中的截取片段。由于确切起止时间未知，导入器不能给出权威的全记录发放率、状态占用率、起止边缘 pause，或断言某状态延伸到采集边界。": "Repeated stimulus or reward events do not automatically establish trials. Continuous data may be an excerpt of a longer recording. Without exact bounds, the importer cannot report authoritative full-recording firing rates, state occupancy, boundary pauses, or claim that a state reaches an acquisition boundary.",
        "数据文件已成功读取，可以继续配置": "Data file read successfully; configuration can continue",
        "当前规范导入不会直接替换主光栅图。完成确认并保存后，可在“手工 ISI 标记与审核”中载入这份数据；主界面继续显示原数据并不表示 CSV 读取失败。": "Canonical import does not directly replace the main raster. After confirmation and saving, load the data in Manual ISI labeling & review; the main view continuing to show earlier data does not mean CSV reading failed.",
        "本页所需信息已全部确认，可以继续设置“列与分组”。": "All required information on this page is confirmed; continue to Columns & groups.",
        "这些是数据含义尚未确认，不表示文件读取失败。您也可以先进入后续页面查看已读取的列。": "These items describe unconfirmed data meaning, not a file-reading failure. You may inspect the loaded columns on later pages first.",
        "等待数据源绑定完成": "Wait for data-source binding to finish",
        "选择数据源时间戳单位": "Select the source timestamp unit",
        "选择活动模式": "Select the activity mode",
        "输入稳定的记录片段 ID": "Enter a stable recording-segment ID",
        "选择记录组织方式": "Select the recording organization",
        "确认导入片段内的数据流覆盖情况": "Confirm data-stream coverage within the imported excerpt",
        "确认确切的记录起止时间未知或无法获得": "Confirm that exact recording bounds are unknown or unavailable",
        "定义数据列和事件组": "Define data columns and event groups",
        "每个源列必须且只能分配一次。每个连续分组必须遵循 S+ E*：一个或多个 spike train，之后可接零个或多个事件列。": "Every source column must be assigned exactly once. Each contiguous group must follow S+ E*: one or more spike trains followed by zero or more event columns.",
        "常见纯 Spike-train 表格的批量设置": "Batch setup for common spike-train-only tables",
        "如果本文件的每一列都是同一次记录中的 spike train，且没有事件列，可用下面的显式操作减少逐列重复设置。系统不会仅凭数值或表头自动套用模板。": "If every column is a spike train from the same recording and there are no event columns, use the explicit actions below to reduce repetitive setup. The template is never inferred from values or headers alone.",
        "套用：全部列属于同一记录经过时间分组": "Apply: all columns belong to one recording-elapsed group",
        "用表头填充尚为空白的列 ID": "Fill empty column IDs from headers",
        "批量设置时间顺序": "Batch timestamp order",
        "全部保留数据源顺序": "Preserve source order for all",
        "全部采用稳定升序排序": "Use stable ascending sort for all",
        "批量设置重复时间戳": "Batch duplicate timestamps",
        "全部保留事件重数": "Preserve event multiplicity for all",
        "全部在单神经元分析视图中虚拟折叠": "Virtually collapse all in single-unit analysis views",
        "单一分组语义 ID": "Single group semantic ID",
        "例如 STN_recording_group": "e.g. STN_recording_group",
        "支持键盘输入、右键粘贴以及 Command-V 粘贴。": "Supports typing, context-menu paste, and Command-V.",
        "套用模板后，仍需确认分组 ID、列 ID、时间顺序和重复时间戳策略。": "After applying the template, confirm group IDs, column IDs, timestamp order, and duplicate-timestamp policy.",
        "确认所有列都是同一记录经过时间分组中的 Spike train？": "Confirm that every column is a spike train in one recording-elapsed group?",
        "确认并套用模板": "Confirm and apply template",
        "取消": "Cancel",
        "该操作会替换当前列角色和分组边界，但不会自动生成科学 ID，也不会替您决定时间顺序或重复时间戳策略。": "This replaces current column roles and group boundaries but does not generate scientific IDs or decide timestamp order or duplicate-timestamp policy.",
        "确认事件属性": "Confirm event attributes",
        "每个键都必须明确指定类型、科学或展示角色、单位决定及空字符串策略。批量分配角色仍会为每个键分别记录决定。": "Every key requires an explicit type, scientific or presentation role, unit decision, and empty-string policy. Batch role assignment still records a separate decision for every key.",
        "发现数据源事实": "Discover source facts",
        "添加属性": "Add attribute",
        "将所选设为：科学属性": "Set selected to scientific attributes",
        "将所选设为：展示属性": "Set selected to presentation attributes",
        "移除所选": "Remove selected",
        "尚无属性定义。可手动添加键，或运行“发现数据源事实”，将事件时间戳旁发现的未确定键加入列表。": "No attributes are defined. Add keys manually or run Discover source facts to add unresolved keys found beside event timestamps.",
        "内联的 @x.unit=… 仅是导入建议。上方经确认的 manifest 单位是唯一权威；发生冲突时将阻止验证。": "Inline @x.unit=… values are import suggestions only. The confirmed manifest unit above is authoritative; conflicts block validation.",
        "事件列元数据语法": "Event-column metadata syntax",
        "每个时间戳开始一次事件 occurrence。同一事件列中连续的 @key=value 行都属于该 occurrence，直到下一个时间戳或空白行为止。仅当 note 被确认为 String 且允许空字符串时，@note= 才表示明确存在的空字符串；省略 @note 行表示该键缺失。.unit 行仅是建议，不能覆盖已确认的 manifest。": "Each timestamp starts an event occurrence. Consecutive @key=value rows in that event column belong to the occurrence until the next timestamp or blank row. @note= denotes an explicit empty string only when note is confirmed as String and empty strings are allowed; omitting @note means the key is absent. .unit rows are suggestions and cannot override the confirmed manifest.",
        "验证前审核": "Pre-validation review",
        "下一步将执行解析 → 精确规范化 → 独立验证，并显示可定位到数据源的阻断项。": "The next step performs parsing → exact normalization → independent validation and shows blocking issues traceable to the source.",
        "当前内容只是待验证的导入草稿，尚未成为已确认的数据集，也不授予分析权限；它不会替换当前活动数据。": "The current content is an unvalidated import draft. It is not a confirmed dataset, grants no analysis authority, and does not replace active data.",
        "请先绑定数据源事实": "Bind source facts first",
        "请在“数据源”中选择工作表和表头规则，然后绑定确切的表格快照。": "Select a worksheet and header rule under Source, then bind the exact table snapshot.",
        "进入人工 ISI 标记与分析": "Enter manual ISI labeling & analysis",
        "关闭": "Close",
        "绑定数据源事实": "Bind source facts",
        "重新绑定数据源事实": "Rebind source facts",
        "运行精确验证": "Run exact validation",
        "确认并保存": "Confirm and save",
        "取消审核": "Cancel review",
        "已保存并验证确认清单。": "Confirmation manifest saved and verified.",
        "此数据源已保存的清单": "Saved manifests for this source",
        "恢复并验证": "Restore & verify",
        "只能在绑定数据源事实之前执行恢复。如需恢复已保存清单，请重新绑定或取消当前操作。": "Restore is available only before binding source facts. To restore a saved manifest, rebind or cancel the current operation.",
        "首行为表头": "First row is header",
        "无表头": "No header",
        "连续记录": "Continuous recording",
        "组织方式未知": "Organization unknown",
        "完整覆盖": "Full coverage",
        "部分覆盖": "Partial coverage",
        "覆盖情况未知": "Coverage unknown",
        "秒": "seconds",
        "毫秒": "milliseconds",
        "确切数据源快照": "Exact data-source snapshot",
        "文件": "File",
        "格式": "Format",
        "大小": "Size",
        "明确的数据源决定": "Explicit source decisions",
        "工作表": "Worksheet",
        "隐藏工作表仍会显示在此列表中，并且必须由用户明确选择。": "Hidden worksheets remain visible in this list and must be selected explicitly.",
        "首个逻辑行": "First logical row",
        "用作列标题": "Use as column headers",
        "作为数据处理（无表头）": "Treat as data (no header)",
        "无表头输入仅限一个记录经过时间分组，且只能包含 spike 列；不允许事件列。": "Headerless input is limited to one recording-elapsed group containing spike columns only; event columns are not allowed.",
        "更改任一决定都会丢弃阶段 B 的全部选择。不同数据源绑定之间不会静默迁移任何内容。": "Changing either decision discards all Stage B choices. Nothing is silently migrated between source bindings.",
        "只读表格预览": "Read-only table preview",
        "行": "Row",
        "分组边界": "Group boundary",
        "延续当前分组": "Continue current group",
        "开始新分组": "Start new group",
        "分组语义 ID": "Group semantic ID",
        "时间基准": "Time basis",
        "记录经过时间": "Recording-elapsed time",
        "事件相对时间": "Event-relative time",
        "原点事件列": "Origin event column",
        "原点数据行": "Origin data row",
        "角色": "Role",
        "事件定义": "Event definition",
        "列语义 ID": "Column semantic ID",
        "事件类型 ID": "Event-type ID",
        "顺序": "Order",
        "顺序未确定": "Order not determined",
        "保留数据源顺序": "Preserve source order",
        "稳定升序排序": "Stable ascending sort",
        "完全重复时间戳": "Exact duplicate timestamps",
        "重复策略未确定": "Duplicate policy not determined",
        "保留事件重数": "Preserve event multiplicity",
        "在单单位分析视图中虚拟折叠": "Virtually collapse in single-unit analysis views",
        "键": "Key",
        "类型": "Type",
        "单位": "Unit",
        "指定符号": "Specified symbol",
        "空字符串": "Empty string",
        "选择属性": "Select attribute",
        "科学属性": "Scientific attribute",
        "展示属性": "Presentation attribute",
        "不适用": "Not applicable",
        "无量纲": "Dimensionless",
        "指定单位": "Specified unit",
        "禁止": "Forbid",
        "允许明确空值": "Allow explicit empty value",
        "人工 ISI 标记与描述性分析可用": "Manual ISI labeling and descriptive analysis available",
        "自动分析权限仍处于锁定状态": "Automatic analysis authority remains locked",
        "该确认数据可以直接进入逐 ISI 人工标记、检查和导出流程。此入口不运行自动检测器，也不会把当前尚未完善的自动算法结果声明为权威结果。": "This confirmed dataset can enter per-ISI manual labeling, inspection, and export directly. This path does not run the automatic detector or present unfinished algorithmic results as authoritative.",
        "只有在所有决定均完成、精确规范化和独立验证均无阻断项，并由用户明确确认后，确定的单神经元电活动数据才可能具备后续资格。多神经元及未知/不确定数据仍只能浏览，不能运行单神经元检测器。": "Confirmed single-unit data become eligible only after all decisions are complete, exact normalization and independent validation have no blockers, and the user confirms explicitly. Multi-unit and unknown/uncertain data remain browse-only and cannot run the single-unit detector.",
        "预检表单阻断项": "Preflight form blockers",
        "可定位到数据源的预检": "Source-traceable preflight",
        "预检发现": "Preflight findings",
        "时间戳事实": "Timestamp facts",
        "分组 / 列": "Group / column",
        "有效数": "Valid",
        "源负值": "Source negatives",
        "逆序数": "Descents",
        "完全重复数": "Exact duplicates",
        "事件": "Events",
        "发现的事件属性": "Discovered event attributes",
        "事件相对时间原点候选": "Event-relative origin candidates",
        "上一页": "Previous page",
        "下一页": "Next page",
        "用作原点": "Use as origin",
        "指定时间戳单位、分组边界和列角色后，请运行“发现数据源事实”。发现的键会被加入列表，但其类型、角色、单位和空值策略仍保持未确定。": "After specifying timestamp units, group boundaries, and column roles, run Discover source facts. Discovered keys are added, but their type, role, unit, and empty-value policy remain unresolved.",
        "尚未对当前草稿运行验证。": "Validation has not been run on the current draft.",
        "表单阻断项": "Form blockers",
        "返回“列与分组”完成设置": "Return to Columns & groups",
        "清单阻断项": "Manifest blockers",
        "返回“数据集含义”完成设置": "Return to Dataset meaning",
        "全部保留重复时间戳": "Preserve all duplicate timestamps",
        "全部采用虚拟折叠": "Use virtual collapse for all",
        "精确数据阻断项": "Exact-data blockers",
        "独立验证阻断项": "Independent-validation blockers",
        "精确规范化和独立验证已通过。": "Exact normalization and independent validation passed.",
        "这仅证明准备值可以复现；不会授予科学权限，也不会更改当前活动数据集。": "This proves only that the prepared values are reproducible; it grants no scientific authority and does not change the active dataset.",
        "可见": "Visible",
        "隐藏": "Hidden",
        "深度隐藏": "Very hidden",
        "字符串": "String",
        "整数": "Integer",
        "精确小数": "Exact decimal",
        "布尔值": "Boolean",
        "您已明确确认本文件代表单神经元活动；这项选择决定后续分析方式，但本身不等同于软件已经证明 spike sorting 或单神经元分离质量。": "You explicitly confirmed that this file represents single-unit activity. This choice governs downstream analysis but does not mean the software has proved spike-sorting or isolation quality.",
        "仅作为实验性占位；不会复用单神经元活动的阈值和检测器。": "Experimental placeholder only; single-unit thresholds and detectors are not reused.",
        "可以审核该表格，但不得产生确定性的生物学解释或权威检测器输出。": "The table can be reviewed, but it cannot produce definitive biological interpretations or authoritative detector output.",
        "请明确选择采集含义；同一个文件不能按列混用不同活动模式。": "Select the acquisition meaning explicitly; one file cannot mix activity modes by column.",
        "规范原始数据始终保留每个重复时间戳。请选择后续单神经元活动分析视图是否可以虚拟折叠完全重复值；数据源和规范数据中的事件重数绝不会被删除。": "Canonical raw data always retain every duplicate timestamp. Decide whether downstream single-unit views may virtually collapse exact duplicates; event multiplicity is never removed from the source or canonical data.",
        "规范原始数据会保留事件重数。多神经元活动和不确定数据不能借用单神经元活动的虚拟折叠策略。": "Canonical raw data retain event multiplicity. Multi-unit and uncertain data cannot borrow the single-unit virtual-collapse policy.",
        "请先选择活动模式，再确认完全重复时间戳的表示方式。": "Select the activity mode before deciding how exact duplicate timestamps are represented.",
        "当前没有导入审核。": "No import review is active.",
        "正在读取确切且受限的数据源快照…": "Reading the exact bounded data-source snapshot…",
        "正在等待明确的阶段 A 决定。": "Waiting for explicit Stage A decisions.",
        "正在绑定所选表格…": "Binding the selected table…",
        "数据源事实已绑定；科学选择仍为草稿。": "Source facts are bound; scientific choices remain a draft.",
        "正在使用 Core 语法扫描精确时间戳和事件元数据…": "Scanning exact timestamps and event metadata with the Core grammar…",
        "正在执行精确规范化和独立验证…": "Running exact normalization and independent validation…",
        "确认清单已保存；可以进入人工 ISI 标记与分析。": "The confirmation manifest is saved; manual ISI labeling and analysis are available.",
        "准备值已验证；自动检测权限仍处于锁定状态。": "Prepared values are validated; automatic detector authority remains locked.",
        "导入未能完成；活动数据集没有改变。": "Import did not complete; the active dataset did not change.",
        "未解析事件 ID": "Unresolved event ID"
    ]

    static let russian: [String: String] = [
        "数据集含义": "Смысл набора данных",
        "列与分组": "Столбцы и группы",
        "事件与属性": "События и атрибуты",
        "审核": "Проверка",
        "绑定数据源": "Привязка источника данных",
        "阶段 A 只记录确切文件、工作表和表头规则，不作任何科学假设。": "Этап A фиксирует только точный файл, лист и правило заголовка, не делая научных предположений.",
        "正在读取受限的数据源快照…": "Чтение ограниченного снимка источника данных…",
        "数据源尚未绑定": "Источник данных не привязан",
        "请关闭此审核并选择受支持的 CSV 或 XLSX 文件。": "Закройте эту проверку и выберите поддерживаемый файл CSV или XLSX.",
        "尚未选择数据源": "Источник данных не выбран",
        "请从工具栏或“文件”菜单选择“导入数据”。": "Выберите «Импорт данных» на панели инструментов или в меню «Файл».",
        "确认数据集含义": "Подтверждение смысла набора данных",
        "这些决定适用于整个文件；不会根据表头或时间戳数值大小推断任何含义。": "Эти решения относятся ко всему файлу; смысл не выводится из заголовков или величины временных меток.",
        "时间戳合同": "Контракт временных меток",
        "数据源时间戳单位": "Единица временных меток источника",
        "未确定": "Не определено",
        "秒（s）": "Секунды (s)",
        "毫秒（ms）": "Миллисекунды (ms)",
        "接受的时间戳必须能精确映射为有符号整数微秒。以秒显示时保留 6 位小数，以毫秒显示时保留 3 位；导入器绝不会静默舍入。记录经过时间为负值时会阻止导入；只有明确确认事件原点后，有符号的事件相对时间戳才可能有效。": "Допустимые временные метки должны точно отображаться в знаковые целые микросекунды. Для секунд сохраняются 6 знаков после запятой, для миллисекунд — 3; импортер никогда не округляет молча. Отрицательное время от начала записи блокирует импорт; знаковые значения относительно события допустимы только после явного подтверждения исходного события.",
        "此文件所表示的活动类型": "Тип активности в файле",
        "活动模式": "Режим активности",
        "更改活动模式会清除每个 spike 列的重复时间戳决定，因为相同时间戳在不同模式下具有不同科学含义。请重新逐项明确确认。": "Смена режима активности сбрасывает решение о повторяющихся временных метках для каждого spike-столбца, поскольку одинаковые метки имеют разный научный смысл в разных режимах. Подтвердите решения заново.",
        "此文件的记录片段": "Сегмент записи в файле",
        "本次导入整体视为一个记录片段，所有 spike train 和事件组均属于该片段。共享同一片段并不意味着时钟或原点不同的分组可以直接比较。": "Весь импорт считается одним сегментом записи, которому принадлежат все spike train и группы событий. Общий сегмент не делает напрямую сопоставимыми группы с разными часами или началами отсчёта.",
        "记录片段 ID": "ID сегмента записи",
        "输入并确认稳定的片段标识符": "Введите и подтвердите стабильный ID сегмента",
        "这是承载科学身份的稳定记录片段标识符。界面默认填入导入文件名（不含 .csv/.xlsx），您可以直接编辑或从外部复制粘贴；最终以确认时界面中的完整文字为准。": "Этот стабильный ID сегмента записи является частью научной идентичности. По умолчанию используется имя импортируемого файла без .csv/.xlsx; его можно редактировать или вставлять. Авторитетен полный текст на момент подтверждения.",
        "文件名只提供可编辑的初始建议，不会被静默清理或改写；非空但无效的标识符会被拒绝。CSV 与 XLSX 扩展名不进入该建议。": "Имя файла — лишь редактируемое начальное предложение; оно не очищается и не переписывается молча. Непустой недопустимый ID отклоняется. Расширения CSV и XLSX не входят в предложение.",
        "记录组织方式": "Организация записи",
        "连续记录，无试次": "Непрерывная запись без проб",
        "按试次组织": "Организация по пробам",
        "导入片段内的 spike-train 覆盖情况": "Покрытие spike train в импортированном фрагменте",
        "所有纳入的 spike-train 数据流在整个导入片段内均持续可观察且有效": "Все включённые потоки spike train непрерывно наблюдаемы и действительны во всём импортированном фрагменте",
        "至少一条纳入的 spike-train 数据流在导入片段内并非全程可观察或有效": "Как минимум один включённый поток spike train наблюдаем или действителен не на всём импортированном фрагменте",
        "完整覆盖表示每条纳入的 spike-train 数据流在整个片段内持续可观察且有效；并不要求片段起止边缘必须出现 spike、数据流必须非空，也不构成单单位分离质量的证明。": "Полное покрытие означает, что каждый включённый поток spike train непрерывно наблюдаем и действителен во всём фрагменте. Оно не требует spike на границах, непустого потока и не доказывает качество выделения одиночного нейрона.",
        "我确认确切的记录起止时间未知或无法获得": "Подтверждаю, что точные начало и конец записи неизвестны или недоступны",
        "重复的刺激或奖赏事件不会自动建立试次。连续数据可能只是较长记录中的截取片段。由于确切起止时间未知，导入器不能给出权威的全记录发放率、状态占用率、起止边缘 pause，或断言某状态延伸到采集边界。": "Повторяющиеся стимулы или награды не создают пробы автоматически. Непрерывные данные могут быть фрагментом более длинной записи. Без точных границ импортер не может авторитетно сообщать частоту по всей записи, занятость состояний, паузы на границах или утверждать, что состояние достигает границы сбора.",
        "数据文件已成功读取，可以继续配置": "Файл данных успешно прочитан; можно продолжить настройку",
        "当前规范导入不会直接替换主光栅图。完成确认并保存后，可在“手工 ISI 标记与审核”中载入这份数据；主界面继续显示原数据并不表示 CSV 读取失败。": "Канонический импорт не заменяет основной растр напрямую. После подтверждения и сохранения данные можно загрузить в разделе ручной разметки и проверки ISI; прежние данные в основном окне не означают ошибку чтения CSV.",
        "本页所需信息已全部确认，可以继续设置“列与分组”。": "Все обязательные данные на странице подтверждены; можно перейти к столбцам и группам.",
        "这些是数据含义尚未确认，不表示文件读取失败。您也可以先进入后续页面查看已读取的列。": "Это неподтверждённый смысл данных, а не ошибка чтения файла. Сначала можно посмотреть прочитанные столбцы на следующих страницах.",
        "等待数据源绑定完成": "Дождитесь завершения привязки источника",
        "选择数据源时间戳单位": "Выберите единицу временных меток источника",
        "选择活动模式": "Выберите режим активности",
        "输入稳定的记录片段 ID": "Введите стабильный ID сегмента записи",
        "选择记录组织方式": "Выберите организацию записи",
        "确认导入片段内的数据流覆盖情况": "Подтвердите покрытие потоков в импортированном фрагменте",
        "确认确切的记录起止时间未知或无法获得": "Подтвердите, что точные границы записи неизвестны или недоступны",
        "定义数据列和事件组": "Определение столбцов данных и групп событий",
        "每个源列必须且只能分配一次。每个连续分组必须遵循 S+ E*：一个或多个 spike train，之后可接零个或多个事件列。": "Каждый столбец источника должен быть назначен ровно один раз. Каждая непрерывная группа должна соответствовать S+ E*: один или несколько spike train, затем ноль или несколько столбцов событий.",
        "常见纯 Spike-train 表格的批量设置": "Пакетная настройка таблиц только со spike train",
        "如果本文件的每一列都是同一次记录中的 spike train，且没有事件列，可用下面的显式操作减少逐列重复设置。系统不会仅凭数值或表头自动套用模板。": "Если каждый столбец — spike train из одной записи и столбцов событий нет, используйте явные действия ниже. Шаблон не применяется автоматически только по значениям или заголовкам.",
        "套用：全部列属于同一记录经过时间分组": "Применить: все столбцы входят в одну группу времени от начала записи",
        "用表头填充尚为空白的列 ID": "Заполнить пустые ID столбцов из заголовков",
        "批量设置时间顺序": "Пакетный порядок временных меток",
        "全部保留数据源顺序": "Сохранить исходный порядок для всех",
        "全部采用稳定升序排序": "Стабильно сортировать все по возрастанию",
        "批量设置重复时间戳": "Пакетная настройка повторяющихся меток",
        "全部保留事件重数": "Сохранить кратность событий для всех",
        "全部在单神经元分析视图中虚拟折叠": "Виртуально свернуть все в представлениях одиночного нейрона",
        "单一分组语义 ID": "Единый семантический ID группы",
        "例如 STN_recording_group": "например, STN_recording_group",
        "支持键盘输入、右键粘贴以及 Command-V 粘贴。": "Поддерживаются ввод, вставка из контекстного меню и Command-V.",
        "套用模板后，仍需确认分组 ID、列 ID、时间顺序和重复时间戳策略。": "После шаблона подтвердите ID групп и столбцов, порядок времени и политику повторяющихся меток.",
        "确认所有列都是同一记录经过时间分组中的 Spike train？": "Подтвердить, что все столбцы — spike train в одной группе времени от начала записи?",
        "确认并套用模板": "Подтвердить и применить шаблон",
        "取消": "Отмена",
        "该操作会替换当前列角色和分组边界，但不会自动生成科学 ID，也不会替您决定时间顺序或重复时间戳策略。": "Операция заменит роли столбцов и границы групп, но не создаст научные ID и не выберет порядок времени или политику повторяющихся меток.",
        "确认事件属性": "Подтверждение атрибутов событий",
        "每个键都必须明确指定类型、科学或展示角色、单位决定及空字符串策略。批量分配角色仍会为每个键分别记录决定。": "Для каждого ключа явно задаются тип, научная или презентационная роль, единица и политика пустой строки. Пакетное назначение всё равно сохраняет отдельное решение для каждого ключа.",
        "发现数据源事实": "Найти факты источника",
        "添加属性": "Добавить атрибут",
        "将所选设为：科学属性": "Назначить выбранные научными атрибутами",
        "将所选设为：展示属性": "Назначить выбранные презентационными атрибутами",
        "移除所选": "Удалить выбранные",
        "尚无属性定义。可手动添加键，或运行“发现数据源事实”，将事件时间戳旁发现的未确定键加入列表。": "Атрибуты не определены. Добавьте ключи вручную или запустите поиск фактов источника, чтобы добавить неопределённые ключи рядом с временными метками событий.",
        "内联的 @x.unit=… 仅是导入建议。上方经确认的 manifest 单位是唯一权威；发生冲突时将阻止验证。": "Встроенные @x.unit=… — только предложения импорта. Подтверждённая единица манифеста выше является единственно авторитетной; конфликт блокирует проверку.",
        "事件列元数据语法": "Синтаксис метаданных столбца событий",
        "每个时间戳开始一次事件 occurrence。同一事件列中连续的 @key=value 行都属于该 occurrence，直到下一个时间戳或空白行为止。仅当 note 被确认为 String 且允许空字符串时，@note= 才表示明确存在的空字符串；省略 @note 行表示该键缺失。.unit 行仅是建议，不能覆盖已确认的 manifest。": "Каждая временная метка начинает occurrence события. Последовательные строки @key=value в том же столбце относятся к нему до следующей метки или пустой строки. @note= означает явную пустую строку только при подтверждённом типе String и разрешённых пустых строках; отсутствие @note означает отсутствие ключа. Строки .unit — предложения и не переопределяют манифест.",
        "验证前审核": "Проверка перед валидацией",
        "下一步将执行解析 → 精确规范化 → 独立验证，并显示可定位到数据源的阻断项。": "Далее выполняются разбор → точная нормализация → независимая проверка с показом блокирующих проблем, привязанных к источнику.",
        "当前内容只是待验证的导入草稿，尚未成为已确认的数据集，也不授予分析权限；它不会替换当前活动数据。": "Текущее содержимое — непроверенный черновик импорта, а не подтверждённый набор данных. Оно не даёт права на анализ и не заменяет активные данные.",
        "请先绑定数据源事实": "Сначала привяжите факты источника",
        "请在“数据源”中选择工作表和表头规则，然后绑定确切的表格快照。": "В разделе источника выберите лист и правило заголовка, затем привяжите точный снимок таблицы.",
        "进入人工 ISI 标记与分析": "Перейти к ручной разметке и анализу ISI",
        "关闭": "Закрыть",
        "绑定数据源事实": "Привязать факты источника",
        "重新绑定数据源事实": "Перепривязать факты источника",
        "运行精确验证": "Запустить точную проверку",
        "确认并保存": "Подтвердить и сохранить",
        "取消审核": "Отменить проверку",
        "已保存并验证确认清单。": "Манифест подтверждения сохранён и проверен.",
        "此数据源已保存的清单": "Сохранённые манифесты источника",
        "恢复并验证": "Восстановить и проверить",
        "只能在绑定数据源事实之前执行恢复。如需恢复已保存清单，请重新绑定或取消当前操作。": "Восстановление доступно только до привязки фактов источника. Чтобы восстановить манифест, перепривяжите источник или отмените текущую операцию.",
        "首行为表头": "Первая строка — заголовок",
        "无表头": "Без заголовка",
        "连续记录": "Непрерывная запись",
        "组织方式未知": "Организация неизвестна",
        "完整覆盖": "Полное покрытие",
        "部分覆盖": "Частичное покрытие",
        "覆盖情况未知": "Покрытие неизвестно",
        "秒": "секунды",
        "毫秒": "миллисекунды",
        "确切数据源快照": "Точный снимок источника",
        "文件": "Файл",
        "格式": "Формат",
        "大小": "Размер",
        "明确的数据源决定": "Явные решения об источнике",
        "工作表": "Лист",
        "隐藏工作表仍会显示在此列表中，并且必须由用户明确选择。": "Скрытые листы остаются в списке и должны выбираться явно.",
        "首个逻辑行": "Первая логическая строка",
        "用作列标题": "Использовать как заголовки",
        "作为数据处理（无表头）": "Обрабатывать как данные (без заголовка)",
        "无表头输入仅限一个记录经过时间分组，且只能包含 spike 列；不允许事件列。": "Ввод без заголовка допускает одну группу времени от начала записи только со spike-столбцами; столбцы событий запрещены.",
        "更改任一决定都会丢弃阶段 B 的全部选择。不同数据源绑定之间不会静默迁移任何内容。": "Изменение любого решения сбрасывает все выборы этапа B. Между привязками источников ничего не переносится молча.",
        "只读表格预览": "Предпросмотр таблицы только для чтения",
        "行": "Строка",
        "分组边界": "Граница группы",
        "延续当前分组": "Продолжить текущую группу",
        "开始新分组": "Начать новую группу",
        "分组语义 ID": "Семантический ID группы",
        "时间基准": "Временная основа",
        "记录经过时间": "Время от начала записи",
        "事件相对时间": "Время относительно события",
        "原点事件列": "Столбец исходного события",
        "原点数据行": "Исходная строка данных",
        "角色": "Роль",
        "事件定义": "Определение события",
        "列语义 ID": "Семантический ID столбца",
        "事件类型 ID": "ID типа события",
        "顺序": "Порядок",
        "顺序未确定": "Порядок не определён",
        "保留数据源顺序": "Сохранить порядок источника",
        "稳定升序排序": "Стабильная сортировка по возрастанию",
        "完全重复时间戳": "Полностью совпадающие метки",
        "重复策略未确定": "Политика повторов не определена",
        "保留事件重数": "Сохранить кратность событий",
        "在单单位分析视图中虚拟折叠": "Виртуально свернуть в представлениях одиночного нейрона",
        "键": "Ключ",
        "类型": "Тип",
        "单位": "Единица",
        "指定符号": "Заданный символ",
        "空字符串": "Пустая строка",
        "选择属性": "Выбрать атрибут",
        "科学属性": "Научный атрибут",
        "展示属性": "Презентационный атрибут",
        "不适用": "Не применимо",
        "无量纲": "Безразмерная",
        "指定单位": "Заданная единица",
        "禁止": "Запретить",
        "允许明确空值": "Разрешить явное пустое значение",
        "人工 ISI 标记与描述性分析可用": "Доступны ручная разметка ISI и описательный анализ",
        "自动分析权限仍处于锁定状态": "Право автоматического анализа остаётся заблокированным",
        "该确认数据可以直接进入逐 ISI 人工标记、检查和导出流程。此入口不运行自动检测器，也不会把当前尚未完善的自动算法结果声明为权威结果。": "Подтверждённые данные могут сразу перейти к ручной разметке, проверке и экспорту по ISI. Этот путь не запускает автоматический детектор и не объявляет незавершённые алгоритмические результаты авторитетными.",
        "只有在所有决定均完成、精确规范化和独立验证均无阻断项，并由用户明确确认后，确定的单神经元电活动数据才可能具备后续资格。多神经元及未知/不确定数据仍只能浏览，不能运行单神经元检测器。": "Подтверждённые данные одиночного нейрона получают право на дальнейшую работу только после всех решений, точной нормализации, независимой проверки без блокеров и явного подтверждения пользователя. Мультиюнитные и неопределённые данные доступны только для просмотра.",
        "预检表单阻断项": "Блокеры формы пред-проверки",
        "可定位到数据源的预检": "Пред-проверка с привязкой к источнику",
        "预检发现": "Результаты пред-проверки",
        "时间戳事实": "Факты временных меток",
        "分组 / 列": "Группа / столбец",
        "有效数": "Допустимые",
        "源负值": "Отрицательные в источнике",
        "逆序数": "Нарушения порядка",
        "完全重复数": "Точные повторы",
        "事件": "Событие",
        "发现的事件属性": "Обнаруженные атрибуты событий",
        "事件相对时间原点候选": "Кандидаты начала отсчёта относительно события",
        "上一页": "Предыдущая страница",
        "下一页": "Следующая страница",
        "用作原点": "Использовать как начало отсчёта",
        "指定时间戳单位、分组边界和列角色后，请运行“发现数据源事实”。发现的键会被加入列表，但其类型、角色、单位和空值策略仍保持未确定。": "После задания единицы времени, границ групп и ролей столбцов запустите поиск фактов источника. Найденные ключи добавятся, но их тип, роль, единица и политика пустых значений останутся неопределёнными.",
        "尚未对当前草稿运行验证。": "Текущий черновик ещё не проверен.",
        "表单阻断项": "Блокеры формы",
        "返回“列与分组”完成设置": "Вернуться к столбцам и группам",
        "清单阻断项": "Блокеры манифеста",
        "返回“数据集含义”完成设置": "Вернуться к смыслу набора данных",
        "全部保留重复时间戳": "Сохранить все повторяющиеся метки",
        "全部采用虚拟折叠": "Виртуально свернуть все",
        "精确数据阻断项": "Блокеры точных данных",
        "独立验证阻断项": "Блокеры независимой проверки",
        "精确规范化和独立验证已通过。": "Точная нормализация и независимая проверка пройдены.",
        "这仅证明准备值可以复现；不会授予科学权限，也不会更改当前活动数据集。": "Это доказывает только воспроизводимость подготовленных значений; научные полномочия не предоставляются, активный набор данных не меняется.",
        "可见": "Показано",
        "隐藏": "Скрытый",
        "深度隐藏": "Глубоко скрытый",
        "字符串": "Строка",
        "整数": "Целое число",
        "精确小数": "Точное десятичное число",
        "布尔值": "Логическое значение",
        "您已明确确认本文件代表单神经元活动；这项选择决定后续分析方式，但本身不等同于软件已经证明 spike sorting 或单神经元分离质量。": "Вы явно подтвердили, что файл представляет активность одиночного нейрона. Это определяет дальнейший анализ, но не означает, что программа доказала качество spike sorting или выделения нейрона.",
        "仅作为实验性占位；不会复用单神经元活动的阈值和检测器。": "Только экспериментальная заготовка; пороги и детекторы одиночного нейрона не переиспользуются.",
        "可以审核该表格，但不得产生确定性的生物学解释或权威检测器输出。": "Таблицу можно проверять, но нельзя получать окончательные биологические интерпретации или авторитетный вывод детектора.",
        "请明确选择采集含义；同一个文件不能按列混用不同活动模式。": "Явно выберите смысл регистрации; в одном файле нельзя смешивать режимы активности по столбцам.",
        "规范原始数据始终保留每个重复时间戳。请选择后续单神经元活动分析视图是否可以虚拟折叠完全重复值；数据源和规范数据中的事件重数绝不会被删除。": "Канонические сырые данные всегда сохраняют каждую повторяющуюся метку. Решите, допустимо ли виртуальное сворачивание точных повторов в дальнейших представлениях одиночного нейрона; кратность событий никогда не удаляется из источника или канонических данных.",
        "规范原始数据会保留事件重数。多神经元活动和不确定数据不能借用单神经元活动的虚拟折叠策略。": "Канонические данные сохраняют кратность событий. Мультиюнитные и неопределённые данные не могут использовать стратегию виртуального сворачивания одиночного нейрона.",
        "请先选择活动模式，再确认完全重复时间戳的表示方式。": "Сначала выберите режим активности, затем способ представления точных повторов.",
        "当前没有导入审核。": "Проверка импорта не активна.",
        "正在读取确切且受限的数据源快照…": "Чтение точного ограниченного снимка источника…",
        "正在等待明确的阶段 A 决定。": "Ожидание явных решений этапа A.",
        "正在绑定所选表格…": "Привязка выбранной таблицы…",
        "数据源事实已绑定；科学选择仍为草稿。": "Факты источника привязаны; научные решения остаются черновиком.",
        "正在使用 Core 语法扫描精确时间戳和事件元数据…": "Сканирование точных временных меток и метаданных событий грамматикой Core…",
        "正在执行精确规范化和独立验证…": "Выполняются точная нормализация и независимая проверка…",
        "确认清单已保存；可以进入人工 ISI 标记与分析。": "Манифест подтверждения сохранён; доступна ручная разметка и анализ ISI.",
        "准备值已验证；自动检测权限仍处于锁定状态。": "Подготовленные значения проверены; право автоматического детектора остаётся заблокированным.",
        "导入未能完成；活动数据集没有改变。": "Импорт не завершён; активный набор данных не изменился.",
        "未解析事件 ID": "Неразрешённый ID события"
    ]
}
